# Change these first
owner: pandhu-rendra # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Panel
    url: https://panel.valarecloud.store
  - name: Billing
    url: https://bill.valarecloud.store
  - name: phpMyAdmin
    url: https://pma.valarecloud.store
  - name: Database
    url: db.valgmsrv.my.id
    check: "tcp-ping"
    port: 3306
  - name: SH-1
    url: 128.199.223.57
    check: "tcp-ping"
    port: 22
  - name: PVL-1
    url: 128.199.189.59
    check: "tcp-ping"
    port: 22
  - name: PVL-2
    url: 152.42.242.111
    check: "tcp-ping"
    port: 22
  - name: PVL-3
    url: 139.59.240.217
    check: "tcp-ping"
    port: 22
  - name: PVL-4
    url: 206.189.82.20
    check: "tcp-ping"
    port: 22
  - name: PVL-5
    url: 146.190.83.60
    check: "tcp-ping"
    port: 22
  - name: PVL-6
    url: 159.223.81.194
    check: "tcp-ping"
    port: 22
  - name: PVL-7
    url: 157.245.156.87
    check: "tcp-ping"
    port: 22
  - name: PVL-8
    url: 152.42.222.129
    check: "tcp-ping"
    port: 22
  - name: PVL-9
    url: 152.42.171.12
    check: "tcp-ping"
    port: 22
  - name: PVN-4
    url: 31.57.224.123
    check: "tcp-ping"
    port: 22
  - name: PVN-5
    url: 103.167.150.155
    check: "tcp-ping"
    port: 22

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.valarecloud.store
  # baseUrl: /your-repo-name
  favicon: https://media.discordapp.net/attachments/1297526444574113855/1363892425055146344/VALARECLOUD_-_POLOSAN.png?ex=6807af4e&is=68065dce&hm=392eebbeae390d6be65464dc6641907b85225f4de4804a02c966b1eca146e0f5&=&format=webp&quality=lossless
  logoUrl: https://media.discordapp.net/attachments/1297526444574113855/1363892425055146344/VALARECLOUD_-_POLOSAN.png?ex=6807af4e&is=68065dce&hm=392eebbeae390d6be65464dc6641907b85225f4de4804a02c966b1eca146e0f5&=&format=webp&quality=lossless
  name: ValareCloud
  introTitle: "This is where all ValareCloud nodes are monitored."
  introMessage: Stay up to date with the latest service updates from ValareCloud
  theme: "night"
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/yvv8eHn6A8
    - title: Website
      href: https://valarecloud.store
    - title: Billing
      href: https://bill.valarecloud.store
    - title: Panel
      href: https://panel.valarecloud.store

i18n:
  footer: Powered by [ValareCloud](https://bill.valarecloud.store)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"          # Setiap hari jam 00:00 UTC
  responseTime: "0 23 * * *"   # Setiap hari jam 23:00 UTC
  staticSite: "0 1 * * *"      # Setiap hari jam 01:00 UTC
  summary: "0 0 * * *"         # Setiap hari jam 00:00 UTC
  updateTemplate: "0 0 * * *"  # Setiap hari jam 00:00 UTC
  updates: "0 3 * * *"         # Setiap hari jam 03:00 UTC
  uptime: "*/5 * * * *"        # Setiap 5 menit
